kind: pipeline
type: docker
name: pi-stretch
platform:
  os: linux
  arch: arm
steps:
- name: fetch
  image: arm32v6/alpine
  commands:
  - apk add git
  - git fetch --tags
  - git submodule update --init --recursive --remote
- name: build
  image: docker
  environment:
    CLOUDSMITH_API_KEY:
      from_secret: CLOUDSMITH_API_KEY
  commands:
    - docker build -f Dockerfile-pi-stretch --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .
---
kind: pipeline
type: docker
name: pi-buster
platform:
  os: linux
  arch: arm
steps:
- name: fetch
  image: arm32v6/alpine
  commands:
  - apk add git
  - git fetch --tags
  - git submodule update --init --recursive --remote
- name: build
  image: docker
  environment:
    CLOUDSMITH_API_KEY:
      from_secret: CLOUDSMITH_API_KEY
  commands:
    - docker build -f Dockerfile-pi-buster --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .
    