language: cpp
cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/
matrix:
  include:
  - os: linux
    dist: bionic
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install devscripts build-essential lintian dh-make
    - sudo apt-get install qtdeclarative5-dev qt5-default libjack-jackd2-dev
    - sudo apt-get install libgstreamer1.0-0 libgstreamer1.0-dev gstreamer1.0-gl gstreamer1.0-alsa gstreamer1.0-plugins-base libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good libgstreamer-plugins-good1.0-dev
    compiler:
    - gcc
    script:
    - echo $TRAVIS_TAG
    - qmake QOpenHD.pro CONFIG+=release
    - make
  - os: osx
    osx_image:  xcode11.2
    before_install:
    - brew install qt5
    - brew link qt5 --force
    - mkdir -p src
    - if ! [ -f ./src/gstreamer-1.0-1.16.1-x86_64.pkg ]; then travis_wait curl -o ./src/gstreamer-1.0-1.16.1-x86_64.pkg https://gstreamer.freedesktop.org/data/pkg/osx/1.16.1/gstreamer-1.0-1.16.1-x86_64.pkg; fi
    - if ! [ -f ./src/gstreamer-1.0-devel-1.16.1-x86_64.pkg ]; then travis_wait curl -o ./src/gstreamer-1.0-devel-1.16.1-x86_64.pkg https://gstreamer.freedesktop.org/data/pkg/osx/1.16.1/gstreamer-1.0-devel-1.16.1-x86_64.pkg; fi
    - sudo installer -package ./src/gstreamer-1.0-1.16.1-x86_64.pkg -target /
    - sudo installer -package ./src/gstreamer-1.0-devel-1.16.1-x86_64.pkg -target /
    script:
    - qmake QOpenHD.pro CONFIG+=release
    - make -j5
  - os: windows
    before_install:
    - dir C:/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.17134.0/x64
    - cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd && cd "C:/Users/travis/build/infincia/QOpenHD" && dir'
    - if ! [ -f ./src/qt-unified-windows-x86-online.exe ]; then  curl -o ./src/qt-unified-windows-x86-online.exe -Lv http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe; fi
    - "./src/qt-unified-windows-x86-online.exe --verbose --script qt-installer-windows.qs"
    - ls -la C:/Qt/5.13.1/msvc2017/bin/qtenv2.bat
    script:
    - cmd.exe /C 'cd && "C:\Qt\5.13.1\msvc2017\bin\qtenv2.bat" && cd && "C:\Program
      Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
      x86 && cd "C:\Users\travis\build\infincia\QOpenHD" && cd && qmake QOpenHD.pro
      && nmake'

