name: Windows Release

on: [push]

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  ARTIFACT:     QOpenHD-Evo.zip

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==2.1.*'
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          setup-python: false
      
      - name: Download JOM
        uses: suisei-cn/actions-download-file@v1
        with:
          url:    http://download.qt.io/official_releases/jom/jom.zip

      - name: Unzip JOM
        run:  |
              7z x jom.zip -ojom
              
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run:  |
              ls D:\a\QOpenHD\Qt\5.15.2\msvc2019_64\bin\
              rm -rf build
              mkdir build
              cd build
              qmake CONFIG+=release ..\QOpenHD.pro
              ..\jom\jom -j2
              ls -a
              cd release
              cd
              cd D:\a\QOpenHD\Qt\5.15.2\msvc2019_64\bin\
              cp *.dll D:\a\QOpenHD\QOpenHD\build\release\
              cd D:\a\QOpenHD\QOpenHD\build\release\
              mkdir platforms
              cd D:\a\QOpenHD\Qt\5.15.2\msvc2019_64\plugins\platforms\
              cp *.dll D:\a\QOpenHD\QOpenHD\build\release\platforms\
              cd D:\a\QOpenHD\Qt\5.15.2\msvc2019_64\qml\
              cp -r * D:\a\QOpenHD\QOpenHD\build\release\platforms\
              cd D:\a\QOpenHD\QOpenHD\build\release\
              rm -Rf Qt3D
              rm -Rf QtBluetooth
              rm -Rf QtDataVisualization
              rm -Rf QtGamepad
              rm -Rf QtNfc
              rm -Rf QtPurchasing
              rm -Rf QtQuick3D
              rm -Rf QtRemoteObjects
              rm -Rf QtScxml
              rm -Rf QtSensors
              rm -Rf QtWebChannel
              rm -Rf QtWebEngine
              rm -Rf QtWebSockets
              rm -Rf QtWebView
              rm -Rf QtWinExtras
              ls -a
              cd
              
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "QOpenHD"
          path: |
            D:\a\QOpenHD\QOpenHD\build\release\


              
              
