name: build_package_rpi 

on:
  push:
  pull_request:
    branches: [ "2.3-evo,2.3-evo-dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Emulating Raspberry Pi 4
      id: qemu
      uses: pguyot/arm-runner-action@v2.5.2
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: QOpenHD
        import_github_env: true
        cpu: cortex-a53
        commands: |
            apt update
            apt install -y curl
            rm -Rf /etc/apt/sources.list.d/openhd*
            apt-get clean
            rm -rf /var/lib/apt/lists/*
            curl -1sLf \
            'https://dl.cloudsmith.io/public/openhd/openhd-2-3-evo/setup.deb.sh' \
            | sudo -E bash
            ls -a
            cd /opt
            cd /opt/QOpenHD
            apt update
            apt install -y git libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good
            # sudo bash install_dep_rpi.sh
            sudo apt install -y openhd-qt
            touch /etc/ld.so.conf.d/qt.conf
            sudo echo "/opt/Qt5.15.4/lib/" > /etc/ld.so.conf.d/qt.conf
            sudo ldconfig
            export PATH="$PATH:/opt/Qt5.15.4/bin/"
            sudo rm -Rf /usr/bin/qmake
            sudo ln -s /opt/Qt5.15.4/bin/qmake /usr/bin/qmake
            sudo ./package.sh armhf raspbian bullseye
            ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "QOpenHd"
        path: |
          QOpenHD/*.deb
          
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-3-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "QOpenHD/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
