name: UbuntuX86BuildTest # Basic test that checks if QOpenHD compiles on x86 ubuntu

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        ls -a
        sudo bash install_dep.sh
        sudo bash install_dep_extra.sh
    - name: Build with make
      run: |
        curl -1sLf \
        'https://dl.cloudsmith.io/public/openhd/openhd-2-2-evo/setup.deb.sh' \
        | sudo -E bash
        sudo apt install -y mavsdk
        sudo ./package.sh x86_64 ubuntu jammy

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "ubuntu"
        release: "jammy"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
       
